global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Threading.Tasks;
global using Brushes = System.Windows.Media.Brushes;
global using Color = System.Windows.Media.Color;
global using Cursors = System.Windows.Input.Cursors;
global using HorizontalAlignment = System.Windows.HorizontalAlignment;
global using VerticalAlignment = System.Windows.VerticalAlignment;
global using MessageBox = System.Windows.MessageBox;
global using Application = System.Windows.Application;
global using Button = System.Windows.Controls.Button;
global using Orientation = System.Windows.Controls.Orientation;
global using DataFormats = System.Windows.DataFormats;
global using DragDropEffects = System.Windows.DragDropEffects;
global using Image = System.Windows.Controls.Image;
global using Pen = System.Drawing.Pen;
